from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    postId=models.TextField(max_length=30)
    name = models.CharField(max_length=80)
    description = models.TextField(max_length=300)
    Writer =models.TextField(max_length=30)
    postingDate = models.DateField()
    postingTime = models.TextField(max_length=50)
    companyField = models.CharField(max_length=50)
    extraField=models.TextField(max_length=50)
    avg1=models.IntegerField()
    avg2=models.IntegerField()
    avg3=models.IntegerField()
    avg4=models.IntegerField()
    avg5=models.IntegerField()
    avg6=models.IntegerField()
    avg7=models.IntegerField()
    avg8=models.IntegerField()
    avg9=models.IntegerField()
    avg10=models.IntegerField()
    avg11=models.IntegerField()
    avg12=models.IntegerField()
    std1=models.IntegerField()
    std2=models.IntegerField()
    std3=models.IntegerField()
    std4=models.IntegerField()
    std5=models.IntegerField()
    std6=models.IntegerField()
    std7=models.IntegerField()
    std8=models.IntegerField()
    std9=models.IntegerField()
    std10=models.IntegerField()
    std11=models.IntegerField()
    std12=models.IntegerField()

class Rating(models.Model):
    ratingId=models.TextField(max_length=30)
    rater = models.TextField(max_length=30)
    postId= models.ForeignKey (Post, on_delete=models.CASCADE)
    stars=models.IntegerField()
    comment=models.TextField(max_length=100)
    ratingDate = models.DateField()
    ratingTime = models.TextField(max_length=50)
    extraField=models.TextField(max_length=50)

class JointoChat(models.Model):
    person = models.TextField(max_length=30)
    textBody=models.TextField(max_length=50)
    dateOfSending = models.DateField()
    timeOfSending = models.TextField(max_length=50)
    extraField=models.TextField(max_length=50)

