# Generated by Django 3.1 on 2020-08-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.TextField(max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=300)),
                ('postingDate', models.DateField()),
                ('postingTime', models.TextField(max_length=50)),
                ('companyField', models.CharField(max_length=50)),
                ('extraField', models.TextField(max_length=50)),
                ('avg1', models.IntegerField()),
                ('avg2', models.IntegerField()),
                ('avg3', models.IntegerField()),
                ('avg4', models.IntegerField()),
                ('avg5', models.IntegerField()),
                ('avg6', models.IntegerField()),
                ('avg7', models.IntegerField()),
                ('avg8', models.IntegerField()),
                ('avg9', models.IntegerField()),
                ('avg10', models.IntegerField()),
                ('avg11', models.IntegerField()),
                ('avg12', models.IntegerField()),
                ('std1', models.IntegerField()),
                ('std2', models.IntegerField()),
                ('std3', models.IntegerField()),
                ('std4', models.IntegerField()),
                ('std5', models.IntegerField()),
                ('std6', models.IntegerField()),
                ('std7', models.IntegerField()),
                ('std8', models.IntegerField()),
                ('std9', models.IntegerField()),
                ('std10', models.IntegerField()),
                ('std11', models.IntegerField()),
                ('std12', models.IntegerField()),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingId', models.TextField(max_length=30)),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(max_length=100)),
                ('ratingDate', models.DateField()),
                ('ratingTime', models.TextField(max_length=50)),
                ('extraField', models.TextField(max_length=50)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backprojectapi.post')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JointoChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textBody', models.TextField(max_length=50)),
                ('dateOfSending', models.DateField()),
                ('timeOfSending', models.TimeField()),
                ('extraField', models.TextField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backprojectapi.post')),
            ],
        ),
    ]
