# Generated by Django 3.1 on 2020-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backprojectapi', '0002_auto_20200819_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointochat',
            name='person',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='Writer',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.TextField(max_length=30),
        ),
    ]
